Enable wayland by default, fallback to X11
flathub/com.bitwarden.desktop pull request #99
Opened 2022-05-05 18:05 UTC by ghisvail

2022-07-07 02:30 UTC, TheEvilSkeleton requested changes

2022-07-07 02:30 UTC, TheEvilSkeleton commented on com.bitwarden.desktop.yaml
> +          - fi
Just my two cent: the structure of it is displeasing. I suggest writing a separate bash script.

2022-09-01 03:41 UTC, DoodlesEpic approved these changes

2022-12-29 16:39 UTC, ghisvail commented
@proletarius101 thanks for the heads up :+1:

2023-01-24 23:03 UTC, alistair23 approved these changes

2023-09-05 11:32 UTC, ghisvail commented
> is there anything blocking this from getting merged?

Users testing it and confirming it works both on Wayland and X11.

2023-09-05 12:01 UTC, taaem commented
@ghisvail I just tested the latest build and there are 2 things that are broken:
1. We need to tell electron where to find the cursors, otherwise the cursor is tiny on wayland. Fix (taken from https://github.com/flathub/org.signal.Signal/blob/master/org.signal.Signal.yaml): 
```yaml
  - --env=XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
```
2. There is an exception because the app can't access the system bus:
```
[2:0905/134918.197642:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: Datei oder Verzeichnis nicht gefunden
```
This can be fixed by allowing the flatpak access to the system bus (see https://github.com/flathub/org.signal.Signal/issues/280):
```yaml
  - --socket=system-bus
```

2023-09-05 12:41 UTC, taaem commented
The second one should not be fixed like that but instead like this (see https://github.com/flathub/com.visualstudio.code/blob/master/com.visualstudio.code.yaml#L26C1-L26C46):
```yaml
  - --system-talk-name=org.freedesktop.login1
```

2023-09-05 12:45 UTC, taaem commented
Sorry for the update again, but according to https://github.com/electron/electron/blob/main/shell/browser/lib/power_observer_linux.cc#L18 the correct fix would be:
```yaml
  - --system-talk-name=org.freedesktop.login1
  - --system-talk-name=org.freedesktop.login1.Manager
```

2023-09-05 12:47 UTC, ghisvail commented
> Sorry for the update again, but according to https://github.com/electron/electron/blob/main/shell/browser/lib/power_observer_linux.cc#L18 the correct fix would be:
> 
> ```yaml
>   - --system-talk-name=org.freedesktop.login1
>   - --system-talk-name=org.freedesktop.login1.Manager
> ```

Thank you for investigating this. Could you submit this fix in a separate PR?

2023-09-05 12:48 UTC, taaem commented
@ghisvail I will in a second :)

2023-09-05 13:02 UTC, taaem commented
@ghisvail should I also add the other fix in the new pr?

2023-09-05 13:41 UTC, ghisvail commented
> 

yes please

2023-09-09 06:18 UTC, ghisvail commented
@taaem could you test it again, now that your changes are in?

2023-09-11 21:43 UTC, taaem commented
@ghisvail everything works for me now on wayland :)

2023-11-08 23:32 UTC, cassidyjames commented
Testing locally on Endless OS on Wayland, and it works. It seems to fix #165 for me as well.

2023-11-12 09:11 UTC, ghisvail commented
Looks like it's working on my X11 session too.

2023-11-12 10:04 UTC, merged